# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/TinyMLaaS-main',
                'doc_host': 'https://JeHugawa.github.io',
                'git_url': 'https://github.com/JeHugawa/TinyMLaaS-main',
                'lib_path': 'TinyMLaaS_main'},
  'syms': {'TinyMLaaS_main.core': {'TinyMLaaS_main.core.foo': ('core.html#foo', 'TinyMLaaS_main/core.py')}}}
