# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Bridge/observing.ipynb.

# %% auto 0
__all__ = ['read_prediction_from_port']

# %% ../nbs/Bridge/observing.ipynb 1
from serial import Serial

# uncomment this when using with MCU
# from .components.device import get_device_port

# %% ../nbs/Bridge/observing.ipynb 2
__all__ = ['read_prediction_from_port']

def read_prediction_from_port(port:str):
    """Reads a single prediction line over serial from the MCU device
    and returns dict containing scores with keys `Person` and `No person`. 
    Returns None if serial fails."""

    try:
        with Serial(port, baudrate=19200, timeout=1) as ser:
            output = ser.readline().decode("ascii").strip()
            parts = output.split(" ")

            return {"1":float(parts[2][:-1]), "0":float(parts[6][:-1])}

    except Exception as the_exception:
        print(the_exception)
        
        return None

