# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% ../00_core.ipynb 2
#| test case CoreTester unittest.TestCase

# %% ../00_core.ipynb 4
import fastcore.test as ft

# %% ../00_core.ipynb 5
def test_say_hello():
    def say_hello(to):
        "Say hello to somebody"
        return f'Hello {to}!'
    
